# Generated by Django 4.2.7 on 2023-11-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jumpserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='主机名称')),
                ('ip', models.GenericIPAddressField(verbose_name='被管理主机的ip')),
                ('username', models.CharField(max_length=48, verbose_name='登录主机用户名')),
                ('password', models.CharField(blank=True, max_length=48, null=True, verbose_name='登录密码')),
                ('ssh_pkey_path', models.CharField(blank=True, max_length=250, null=True, verbose_name='密钥的存储路径')),
                ('is_deleted', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='Jumpserver.organization')),
            ],
            options={
                'db_table': 'js_host',
            },
        ),
    ]
